
sendInfoMessage("Registered localization info, checking value ", "default.luam")

return {
	descriptions = {		
		Joker = {						
			--#endregion
		},
		FoxPokerHand = {
			phd_fox_cosmocanyon = {
				name = "Cosmo Canyon",
				text = {
					"3 or more cards divisble by {C:attention}XIII{}",
				},
			}
		}
	},
	misc = {
		challenge_names = {
			c_joy_mystic_wok = "Mystic Wok",
			c_joy_mistake = "Mistake",
			c_joy_monster_reborn = "Monster Reborn",
		},
		v_text = {
			ch_c_joy_gy_start = {
				"Start with some cards in the {C:attention}GY{}",
			},
		},
		poker_hands = {
			joy_eldlixir = "Eldlixir",
			fox_cosmocanyon = "Cosmo Canyon"
		},
		poker_hand_descriptions = {
			joy_eldlixir = {
				"5 Gold cards",
				"(Must be enabled by an ability)"
			},
			["Cosmo Canyon"] =  {
				"3 or more cards divisble by {C:attention}XIII{}",
			}
		},
		dictionary = {
			k_joy_extra_deck = "Extra Deck",
			k_joy_summon_conditions = "Summoning Conditions",
			k_joy_graveyard = "Graveyard",
			k_joy_banishment = "Banishment",
			k_joy_column = "Column",
			k_joy_flipped = "Flipped:",
			k_joy_banish_blind_selected = "Start of Blind",
			k_joy_banish_end_of_round = "End of Round",
			k_joy_banish_boss_selected = "Start of Boss Blind",
			k_joy_banish_end_of_ante = "End of Ante",
			k_joy_select_materials = "Select Materials",
			k_joy_select_tributes = "Select Tributes",
			k_joy_transferred_abilities = "Transferred Abilities:",
			k_joy_select = "Select",
			k_joy_summon = "Summon",
			k_joy_detach = "Detach",
			k_joy_activate = "Activate",
			k_joy_activated_ex = "Activated!",
			k_joy_token = "Token",
			k_joy_disable_tooltips = "Disable glossary tooltips",
			k_joy_disable_booster_tag = "Disable Booster Tag from appearing naturally",
			k_joy_only_ygo_cards = "Only Monster Cards appear",
			k_joy_extra_ygo_booster = "Extra Monster Card booster each shop",
			k_joy_splash = "Splash!",
			k_joy_defeated = "Defeated!",
			k_joy_banished = "Banished!",
			k_joy_flip = "Flip!",
			k_joy_set = "Set!",
			k_joy_revive = "Revive!",
			k_joy_mill = "Mill!",
			k_joy_add = "Add!",
			k_joy_return = "Return!",
			k_joy_booster_group = "Monster Pack",
			k_joy_related = "Related",
			k_joy_monster_tag_default = "a Monster Joker",
			k_joy_glossary = "Basic Glossary",
			k_joy_summon_glosary = "Summon Glossary",
			k_joy_credits = "Credits",
			k_joy_discord = "Discord",
			k_joy_github = "Github",
			--#region Card types
			k_joy_Aqua = "Aqua",
			k_joy_Beast = "Beast",
			k_joy_BeastWarrior = "Beast-Warrior",
			k_joy_CreatorGod = "Creator God",
			k_joy_Cyberse = "Cyberse",
			k_joy_Dinosaur = "Dinosaur",
			k_joy_DivineBeast = "Divine-Beast",
			k_joy_Dragon = "Dragon",
			k_joy_Fairy = "Fairy",
			k_joy_Fiend = "Fiend",
			k_joy_Fish = "Fish",
			k_joy_Illusion = "Illusion",
			k_joy_Insect = "Insect",
			k_joy_Machine = "Machine",
			k_joy_Plant = "Plant",
			k_joy_Psychic = "Psychic",
			k_joy_Pyro = "Pyro",
			k_joy_Reptile = "Reptile",
			k_joy_Rock = "Rock",
			k_joy_SeaSerpent = "Sea Serpent",
			k_joy_Spellcaster = "Spellcaster",
			k_joy_Thunder = "Thunder",
			k_joy_Warrior = "Warrior",
			k_joy_WingedBeast = "Winged-Beast",
			k_joy_Wyrm = "Wyrm",
			k_joy_Zombie = "Zombie",
			k_joy_effect = "Effect",
			k_joy_normal = "Normal",
			k_joy_tuner = "Tuner",
			k_joy_pendulum = "Pendulum",
			k_joy_FUSION = "Fusion",
			k_joy_RITUAL = "Ritual",
			k_joy_SYNCHRO = "Synchro",
			k_joy_XYZ = "Xyz",
			k_joy_LINK = "Link",
			k_joy_LIGHT = "LIGHT",
			k_joy_DARK = "DARK",
			k_joy_WATER = "WATER",
			k_joy_FIRE = "FIRE",
			k_joy_EARTH = "EARTH",
			k_joy_WIND = "WIND",
			k_joy_DIVINE = "DIVINE",
			k_joy_spell = "Spell",
			k_joy_trap = "Trap",
			k_joy_fieldspell = "Field Spell",
			--#endregion
			--#region Archetypes
			k_joy_archetype_dmaid = "Dragonmaid",
			k_joy_archetype_ltwin = "Live☆Twin",
			k_joy_archetype_dogma = "Dogmatika",
			k_joy_archetype_yokai = "Ghost Girls",
			k_joy_archetype_spright = "Spright",
			k_joy_archetype_mekk = "Mekk-Knight",
			k_joy_archetype_generaider = "Generaider",
			k_joy_archetype_fish = "Ghoti",
			k_joy_archetype_psy = "PSY-Frame",
			k_joy_archetype_runick = "Runick",
			k_joy_archetype_ba = "Burning Abyss",
			k_joy_archetype_lab = "Labrynth",
			k_joy_archetype_sub = "Subterror",
			k_joy_archetype_eld = "Eldlich",
			k_joy_archetype_ignis = "@Ignister",
			k_joy_archetype_solfa = "Solfachord",
			k_joy_archetype_witch = "Witchcrafter",
			k_joy_archetype_shaddoll = "Shaddoll",
			k_joy_archetype_paleo = "Paleozoic",
			k_joy_archetype_invoked = "Invoked",
			k_joy_archetype_danger = "Danger!",
			k_joy_archetype_adaman = "Adamancipator",
			k_joy_archetype_misc = "Free Agents",
			k_joy_archetype_token = "Tokens",
			--#endregion
		}
	},
}
